# <font color='blue'>Trabalho Final de Tópicos Avançados em Gestão de Dados</font>
##### Turma 168 - 2020/2
## *Prof. Dr. Rodrigo Espindola*

## Alunos
#### <font color='orange'>*Robson Andrei dos Santos - 13205021-2 robson.andrei@edu.pucrs.br*</font>
#### <font color='orange'>*Diego Cansi Matté - 08104810-0 diego.matte@edu.pucrs.br* </font>

O trabalho final desta disciplina consiste na construção de um modelo preditivo de classificação através do emprego das técnicas de aprendizagem supervisionada usando redes neurais artificiais vistas em aula. As técnicas a serem empregadas precisam ser obrigatoriamente aquelas estudadas em aula nesta disciplina, nesta turma, neste semestre. O trabalho deve ser realizado em duplas. Para isto, cada dupla de alunos(as) deve:

   ###### Escolher uma base de dados disponível publicamente
   https://archive.ics.uci.edu/ml/datasets/abalone
   
   https://datahub.io/machine-learning/abalone#resource-abalone_zip
   
   Objetivo desta base: prever a idade do abalone a partir de medições físicas. A idade do abalone é determinada cortando a concha através do cone, colorindo-a e contando o número de anéis através de um microscópio - uma tarefa tediosa e demorada. Outras medidas, mais fáceis de obter, são utilizadas para prever a idade.

Dos dados originais, os exemplos com valores ausentes foram removidos (a maioria tendo o valor predito ausente) e os intervalos dos valores contínuos foram escalados para uso com uma ANN (dividindo por 200).


Informações sobre o atributo:

É fornecido o nome do atributo, o tipo de atributo, a unidade de medida e uma breve descrição. O número de toques é o valor a prever: seja como um valor contínuo ou como um problema de classificação.



Nome / Tipo de dados / Unidade de medida / Descrição
-----------------------------
Sexo / nominal / - / M, F e I (infantil)

Comprimento / contínuo / mm / Medida de casca mais longa

Diâmetro / contínua / mm / perpendicular ao comprimento

Altura / contínua / mm / com carne na casca

Peso inteiro / contínuo / gramas / abalone inteiro

Peso descascado / contínuo / gramas /

Peso das vísceras da carne / contínuo / gramas / peso intestinal (após sangramento)

Peso da casca / contínuo / gramas / após secagem

Toques / inteiro / +1,5 fornece a idade em anos



<img alt="H. asinina, do Indo-Pacífico, é considerada a espécie-tipo do gênero Haliotis.[1][2]" src="//upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Haliotis_asinina_01.JPG/280px-Haliotis_asinina_01.JPG" decoding="async" width="280" height="243" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Haliotis_asinina_01.JPG/420px-Haliotis_asinina_01.JPG 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Haliotis_asinina_01.JPG/560px-Haliotis_asinina_01.JPG 2x" data-file-width="6000" data-file-height="5216">

<div id="mwe_player_0" class="PopUpMediaTransform" style="width:220px;" videopayload="<div class=&quot;mediaContainer&quot; style=&quot;width:640px&quot;><video id=&quot;mwe_player_1&quot; poster=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/7/70/Haliotis_tuberculata.ogv/640px--Haliotis_tuberculata.ogv.jpg&quot; controls=&quot;&quot; preload=&quot;none&quot; autoplay=&quot;&quot; style=&quot;width:640px;height:480px&quot; class=&quot;kskin&quot; data-durationhint=&quot;10.046511627907&quot; data-startoffset=&quot;0&quot; data-mwtitle=&quot;Haliotis_tuberculata.ogv&quot; data-mwprovider=&quot;wikimediacommons&quot;><source src=&quot;//upload.wikimedia.org/wikipedia/commons/transcoded/7/70/Haliotis_tuberculata.ogv/Haliotis_tuberculata.ogv.480p.webm&quot; type=&quot;video/webm; codecs=&amp;quot;vp8, vorbis&amp;quot;&quot; data-title=&quot;WebM SD (480P)&quot; data-shorttitle=&quot;WebM 480P&quot; data-transcodekey=&quot;480p.webm&quot; data-width=&quot;640&quot; data-height=&quot;480&quot; data-bandwidth=&quot;1090848&quot; data-framerate=&quot;25.083333333333&quot;/><source src=&quot;//upload.wikimedia.org/wikipedia/commons/transcoded/7/70/Haliotis_tuberculata.ogv/Haliotis_tuberculata.ogv.480p.vp9.webm&quot; type=&quot;video/webm; codecs=&amp;quot;vp9, opus&amp;quot;&quot; data-title=&quot;VP9 SD (480P)&quot; data-shorttitle=&quot;VP9 480P&quot; data-transcodekey=&quot;480p.vp9.webm&quot; data-width=&quot;640&quot; data-height=&quot;480&quot; data-bandwidth=&quot;1156432&quot; data-framerate=&quot;25.083333333333&quot;/><source src=&quot;//upload.wikimedia.org/wikipedia/commons/7/70/Haliotis_tuberculata.ogv&quot; type=&quot;video/ogg; codecs=&amp;quot;theora, vorbis&amp;quot;&quot; data-title=&quot;Ficheiro Ogg original, 640 × 480 (1,89 Mbps)&quot; data-shorttitle=&quot;Fonte Ogg&quot; data-width=&quot;640&quot; data-height=&quot;480&quot; data-bandwidth=&quot;1887186&quot; data-framerate=&quot;25.083333333333&quot;/><source src=&quot;//upload.wikimedia.org/wikipedia/commons/transcoded/7/70/Haliotis_tuberculata.ogv/Haliotis_tuberculata.ogv.120p.vp9.webm&quot; type=&quot;video/webm; codecs=&amp;quot;vp9, opus&amp;quot;&quot; data-title=&quot;VP9 da menor largura de banda(120P)&quot; data-shorttitle=&quot;VP9 120P&quot; data-transcodekey=&quot;120p.vp9.webm&quot; data-width=&quot;160&quot; data-height=&quot;120&quot; data-bandwidth=&quot;195208&quot; data-framerate=&quot;25.083333333333&quot;/><source src=&quot;//upload.wikimedia.org/wikipedia/commons/transcoded/7/70/Haliotis_tuberculata.ogv/Haliotis_tuberculata.ogv.160p.webm&quot; type=&quot;video/webm; codecs=&amp;quot;vp8, vorbis&amp;quot;&quot; data-title=&quot;WebM de baixa largura de banda (160P)&quot; data-shorttitle=&quot;WebM 160P&quot; data-transcodekey=&quot;160p.webm&quot; data-width=&quot;214&quot; data-height=&quot;160&quot; data-bandwidth=&quot;221552&quot; data-framerate=&quot;25.083333333333&quot;/><source src=&quot;//upload.wikimedia.org/wikipedia/commons/transcoded/7/70/Haliotis_tuberculata.ogv/Haliotis_tuberculata.ogv.180p.vp9.webm&quot; type=&quot;video/webm; codecs=&amp;quot;vp9, opus&amp;quot;&quot; data-title=&quot;VP9 de baixa largura de banda (180P)&quot; data-shorttitle=&quot;VP9 180P&quot; data-transcodekey=&quot;180p.vp9.webm&quot; data-width=&quot;240&quot; data-height=&quot;180&quot; data-bandwidth=&quot;281640&quot; data-framerate=&quot;25.083333333333&quot;/><source src=&quot;//upload.wikimedia.org/wikipedia/commons/transcoded/7/70/Haliotis_tuberculata.ogv/Haliotis_tuberculata.ogv.240p.webm&quot; type=&quot;video/webm; codecs=&amp;quot;vp8, vorbis&amp;quot;&quot; data-title=&quot;WebM pequeno (240P)&quot; data-shorttitle=&quot;WebM 240P&quot; data-transcodekey=&quot;240p.webm&quot; data-width=&quot;320&quot; data-height=&quot;240&quot; data-bandwidth=&quot;329096&quot; data-framerate=&quot;25.083333333333&quot;/><source src=&quot;//upload.wikimedia.org/wikipedia/commons/transcoded/7/70/Haliotis_tuberculata.ogv/Haliotis_tuberculata.ogv.240p.vp9.webm&quot; type=&quot;video/webm; codecs=&amp;quot;vp9, opus&amp;quot;&quot; data-title=&quot;VP9 pequeno (240P)&quot; data-shorttitle=&quot;VP9 240P&quot; data-transcodekey=&quot;240p.vp9.webm&quot; data-width=&quot;320&quot; data-height=&quot;240&quot; data-bandwidth=&quot;389560&quot; data-framerate=&quot;25.083333333333&quot;/><source src=&quot;//upload.wikimedia.org/wikipedia/commons/transcoded/7/70/Haliotis_tuberculata.ogv/Haliotis_tuberculata.ogv.360p.webm&quot; type=&quot;video/webm; codecs=&amp;quot;vp8, vorbis&amp;quot;&quot; data-title=&quot;WebM para web streaming (360P)&quot; data-shorttitle=&quot;WebM 360P&quot; data-transcodekey=&quot;360p.webm&quot; data-width=&quot;480&quot; data-height=&quot;360&quot; data-bandwidth=&quot;578000&quot; data-framerate=&quot;25.083333333333&quot;/><source src=&quot;//upload.wikimedia.org/wikipedia/commons/transcoded/7/70/Haliotis_tuberculata.ogv/Haliotis_tuberculata.ogv.360p.vp9.webm&quot; type=&quot;video/webm; codecs=&amp;quot;vp9, opus&amp;quot;&quot; data-title=&quot;VP9 (360P)&quot; data-shorttitle=&quot;VP9 360P&quot; data-transcodekey=&quot;360p.vp9.webm&quot; data-width=&quot;480&quot; data-height=&quot;360&quot; data-bandwidth=&quot;633544&quot; data-framerate=&quot;25.083333333333&quot;/></video></div>"><img alt="Ficheiro:Haliotis tuberculata.ogv" style="width:220px;height:165px" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/70/Haliotis_tuberculata.ogv/220px--Haliotis_tuberculata.ogv.jpg"><a href="//upload.wikimedia.org/wikipedia/commons/7/70/Haliotis_tuberculata.ogv" title="Reproduzir conteúdo" target="new"><span class="play-btn-large"><span class="mw-tmh-playtext">Reproduzir conteúdo</span></span></a></div>


#### *Coluna alvo do modelo*
<font color='blue'>Coluna alvo escolhida foi </font>
<font color='red'>*Class_number_of_rings*</font>
<font color='blue'> - Esta coluna contém o resultado do cálculo acrecido de 1,5 para indicar a idade do Abalone.</font>


In [ ]:
#### *Objetivo do modelo preditivo e justificativa*
<font color='blue'>O objetivo do modelo é predizer a idade do Abalone, por conta das características apresentadas como; peso, tamanho, etc, pretendemos apresentar um modelo que seja capaz de predizer a idade usando um modelo de classificação dividindo a idades em dois grupos, Abalones com idade <font color='red'>menores de dez anos </font>de idade e <font color='red'>maiores de dez anos</font>, lembrando que a idade do abalone pode variar de um a vinte anos.</font>
<font color='red'>Justificamos</font> <font color='blue'>a escolha deste objetivo por conta que o Abalone é um molusco de alta procura, e que sustenta um mercado milionário, sua pesca de maneira descontrolada e ilegal trás sérios  prejuízos a sua proliferação, e a sustentação de pescadores credenciados que tem licença para a pesca,  controladas por meio de cotas sustentáveis, como o processo para determinar a idade do molusco é trabalhosa e demorada, envolvendo uma análise física, sendo necessária o corte da concha, e a coloração dos seus anéis por meio do uso de um processo microscópico, justificamos o uso do modelo para a  predição da sua idade de maneira  mais fácil.</font>




#### <font color='red'>*Análise exploratória dos dados*</font>

In [50]:
import pandas as pd
import numpy as np
dados = pd.read_csv("Abalone/abalone_zip/data/abalone_csv.csv");
dados.head()

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  Viscera_weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell_weight  Class_number_of_rings  
0         0.150                     15  
1         0.070                      7  
2         0.210                      9  
3         0.155                     10  
4         0.055                      7

In [51]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Sex                    4177 non-null   object 
 1   Length                 4177 non-null   float64
 2   Diameter               4177 non-null   float64
 3   Height                 4177 non-null   float64
 4   Whole_weight           4177 non-null   float64
 5   Shucked_weight         4177 non-null   float64
 6   Viscera_weight         4177 non-null   float64
 7   Shell_weight           4177 non-null   float64
 8   Class_number_of_rings  4177 non-null   int64  
dtypes: float64(7), int64(1), object(1)
memory usage: 293.8+ KB


In [52]:
dados.shape

(4177, 9)

In [53]:
dados['Class_number_of_rings'].head(10)

0    15
1     7
2     9
3    10
4     7
5     8
6    20
7    16
8     9
9    19
Name: Class_number_of_rings, dtype: int64

##### Escolha da coluna alvo

In [54]:
col_alvo = dados['Class_number_of_rings'];
col_alvo

0       15
1        7
2        9
3       10
4        7
        ..
4172    11
4173    10
4174     9
4175    10
4176    12
Name: Class_number_of_rings, Length: 4177, dtype: int64

*Dados faltantes*

In [55]:
faltantes = dados.isnull().sum()#Soma dos dados faltantes
faltantes
# Soma das linhas onde tem algum dado faltante de acordo com a coluna
# Excluindo colunas desnecessárias 

Sex                      0
Length                   0
Diameter                 0
Height                   0
Whole_weight             0
Shucked_weight           0
Viscera_weight           0
Shell_weight             0
Class_number_of_rings    0
dtype: int64

#### <font color='red'>*Pré-processamento dos dados*</font>

Como nossos atributos numéricos já se encontram em medidas padronizadas, milímetros e gramas, o pré-processamento dos dados fica ainda mais simples.


In [56]:
feature_names = ['Length', 
                 'Diameter',
                 'Height',
                 'Whole_weight',
                 'Shucked_weight',
                 'Viscera_weight',
                 'Shell_weight']
feature_names

['Length',
 'Diameter',
 'Height',
 'Whole_weight',
 'Shucked_weight',
 'Viscera_weight',
 'Shell_weight']

In [57]:
X = dados[feature_names]
X.head()

Length  Diameter  Height  Whole_weight  Shucked_weight  Viscera_weight  \
0   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell_weight  
0         0.150  
1         0.070  
2         0.210  
3         0.155  
4         0.055

In [58]:
print("Total de atributos preditivos até aqui: ", np.size(feature_names))

Total de atributos preditivos até aqui:  7


Pré-processamento dos dados categórico...

In [59]:
from sklearn.preprocessing import LabelBinarizer
lb_sex = LabelBinarizer()
sex = lb_sex.fit_transform(dados['Sex'].values)
print("Classes aprendidas: ",lb_sex.classes_)
print("Dados: ")
print(sex)
X = np.c_[X, sex ]
X
feature_names = np.append(feature_names,lb_sex.classes_)
feature_names
print("Total de atributos preditivos até aqui: ", np.size(feature_names))


Classes aprendidas:  ['F' 'I' 'M']
Dados: 
[[0 0 1]
 [0 0 1]
 [1 0 0]
 ...
 [0 0 1]
 [1 0 0]
 [0 0 1]]
Total de atributos preditivos até aqui:  10


#### Pré-processamento da coluna alvo

Apenas para atributos maiores ou iguais a 10 anos

In [60]:
col_alvo.head(10)

0    15
1     7
2     9
3    10
4     7
5     8
6    20
7    16
8     9
9    19
Name: Class_number_of_rings, dtype: int64

In [61]:
y = dados['Class_number_of_rings'] >= 10
y.head(10)

0     True
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8    False
9     True
Name: Class_number_of_rings, dtype: bool

#### Resultado do pré processamento

In [62]:
X.shape

(4177, 10)

In [63]:
y.shape

(4177,)

In [64]:
X.size

41770

In [65]:
y.size

4177

In [66]:
X

array([[0.455, 0.365, 0.095, ..., 0.   , 0.   , 1.   ],
       [0.35 , 0.265, 0.09 , ..., 0.   , 0.   , 1.   ],
       [0.53 , 0.42 , 0.135, ..., 1.   , 0.   , 0.   ],
       ...,
       [0.6  , 0.475, 0.205, ..., 0.   , 0.   , 1.   ],
       [0.625, 0.485, 0.15 , ..., 1.   , 0.   , 0.   ],
       [0.71 , 0.555, 0.195, ..., 0.   , 0.   , 1.   ]])

In [67]:
y

0        True
1       False
2       False
3        True
4       False
        ...  
4172     True
4173     True
4174    False
4175     True
4176     True
Name: Class_number_of_rings, Length: 4177, dtype: bool

Não aplicamos PCA para a redução da dimencionalidade por se tratar de uma base dedados passivel de ser processada em uma máquina doméstica, e pelo seu volume de dados ser considerado pequeno a médio porte, se tratando de volume de dados e dimensionalidade assim como não sera necessário o uso do K-MEANS para redução da dimensionalidade.

#### Separando os conjuntos de treino e teste

In [68]:
nomes_atributos_numericos   = ['Length','Diameter','Height','Whole_weight','Shucked_weight','Viscera_weight','Shell_weight']
nomes_atributos_categoricos = ['Sex']

In [69]:
from sklearn.model_selection import train_test_split
dados_treino, dados_teste = train_test_split(dados, test_size=0.2, random_state=42)


dados_treino_labels = dados_treino['Class_number_of_rings'].copy()
dados_treino        = dados_treino.drop(columns='Class_number_of_rings')


dados_teste_labels = dados_teste['Class_number_of_rings'].copy()
dados_teste        = dados_teste.drop(columns='Class_number_of_rings')



#### Pré-processamento (automatizado)

In [70]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

pipeline_atr_numericos = Pipeline([
    ('imputer',SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler()),
])

preproc_completo = ColumnTransformer([
    ('numericos',   pipeline_atr_numericos, nomes_atributos_numericos),
    ('categoricos', OneHotEncoder(),        nomes_atributos_categoricos),
    ], 
    sparse_threshold=0)

# pre-processamento do conjunto de treino
X_treino = preproc_completo.fit_transform(dados_treino)

# pre-processamento do conjunto de teste
X_teste = preproc_completo.transform(dados_teste)

# pre-processamento da coluna alvo para treno
y_treino = dados_treino_labels.values >= 10

# pre-processamento da coluna alvo para teste
y_teste = dados_teste_labels.values >= 10

In [71]:
X_treino.shape

(3341, 10)

In [72]:
y_treino.shape

(3341,)

In [73]:
X_teste.shape

(836, 10)

In [74]:
y_teste.shape

(836,)

#### Treinamento e avaliação de desempenho

In [75]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

#### Com regressão linear (apenas para comparar)

In [76]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_treino, y_treino)

y_previsto = log_reg.predict(X_teste)

print("Acurácia: ", accuracy_score(y_teste,y_previsto))
print("Precisão: ", precision_score(y_teste,y_previsto))
print("Recall:   ", recall_score(y_teste,y_previsto))
print("F1 Score: ", f1_score(y_teste,y_previsto))

Acurácia:  0.7978468899521531
Precisão:  0.7985436893203883
Recall:    0.7927710843373494
F1 Score:  0.7956469165659009


#### Treinamento com árvore de decisão (apenas para comparar)

In [77]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

tree_clf = DecisionTreeClassifier(max_depth=2)
tree_clf.fit(X_treino, y_treino)

y_pred = tree_clf.predict(X_teste)

print("Acurácia: ", accuracy_score(y_teste,y_previsto))
print("Precisão: ", precision_score(y_teste,y_previsto))
print("Recall:   ", recall_score(y_teste,y_previsto))
print("F1 Score: ", f1_score(y_teste,y_previsto))

Acurácia:  0.7978468899521531
Precisão:  0.7985436893203883
Recall:    0.7927710843373494
F1 Score:  0.7956469165659009


#### <font color='red'>*Definição da arquitetura das redes neurais artificiais a serem desenvolvidas*</font>

#### Treinamento de uma RNA tipo Multi-Layer Perceptron

In [78]:
from sklearn.neural_network import MLPClassifier

mlp_clf = MLPClassifier(hidden_layer_sizes=(10))
mlp_clf.fit(X_treino, y_treino)

y_previsto = mlp_clf.predict(X_teste)
print("MLP:")
print("Acurácia: ", accuracy_score(y_teste,y_previsto))
print("Precisão: ", precision_score(y_teste,y_previsto))
print("Recall:   ", recall_score(y_teste,y_previsto))
print("F1 Score: ", f1_score(y_teste,y_previsto))

MLP:
Acurácia:  0.7990430622009569
Precisão:  0.7892271662763466
Recall:    0.8120481927710843
F1 Score:  0.8004750593824228


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [79]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(20,4))
mlp_clf.fit(X_treino, y_treino)

y_previsto = mlp_clf.predict(X_teste)
print("MLP:")
print("Acurácia: ", accuracy_score(y_teste,y_previsto))
print("Precisão: ", precision_score(y_teste,y_previsto))
print("Recall:   ", recall_score(y_teste,y_previsto))
print("F1 Score: ", f1_score(y_teste,y_previsto))

MLP:
Acurácia:  0.7966507177033493
Precisão:  0.7842227378190255
Recall:    0.8144578313253013
F1 Score:  0.7990543735224587


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [80]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(10,10,10),activation="logistic")
mlp_clf.fit(X_treino, y_treino)

y_previsto = mlp_clf.predict(X_teste)
print("MLP:")
print("Acurácia: ", accuracy_score(y_teste,y_previsto))
print("Precisão: ", precision_score(y_teste,y_previsto))
print("Recall:   ", recall_score(y_teste,y_previsto))
print("F1 Score: ", f1_score(y_teste,y_previsto))

MLP:
Acurácia:  0.7822966507177034
Precisão:  0.765375854214123
Recall:    0.8096385542168675
F1 Score:  0.7868852459016394


In [81]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(1),activation="logistic")
mlp_clf.fit(X_treino, y_treino)

y_previsto = mlp_clf.predict(X_teste)
print("MLP:")
print("Acurácia: ", accuracy_score(y_teste,y_previsto))
print("Precisão: ", precision_score(y_teste,y_previsto))
print("Recall:   ", recall_score(y_teste,y_previsto))
print("F1 Score: ", f1_score(y_teste,y_previsto))

MLP:
Acurácia:  0.7727272727272727
Precisão:  0.7505567928730512
Recall:    0.8120481927710843
F1 Score:  0.7800925925925927


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [82]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(5),activation="logistic")
mlp_clf.fit(X_treino, y_treino)

y_previsto = mlp_clf.predict(X_teste)
print("MLP:")
print("Acurácia: ", accuracy_score(y_teste,y_previsto))
print("Precisão: ", precision_score(y_teste,y_previsto))
print("Recall:   ", recall_score(y_teste,y_previsto))
print("F1 Score: ", f1_score(y_teste,y_previsto))

MLP:
Acurácia:  0.7727272727272727
Precisão:  0.7368421052631579
Recall:    0.8433734939759037
F1 Score:  0.7865168539325843


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [83]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(5, 10),activation="logistic")
mlp_clf.fit(X_treino, y_treino)

y_previsto = mlp_clf.predict(X_teste)
print("MLP:")
print("Acurácia: ", accuracy_score(y_teste,y_previsto))
print("Precisão: ", precision_score(y_teste,y_previsto))
print("Recall:   ", recall_score(y_teste,y_previsto))
print("F1 Score: ", f1_score(y_teste,y_previsto))

MLP:
Acurácia:  0.7870813397129187
Precisão:  0.7749419953596288
Recall:    0.8048192771084337
F1 Score:  0.789598108747045


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [84]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(20,10,20),activation="logistic")
mlp_clf.fit(X_treino, y_treino)

y_previsto = mlp_clf.predict(X_teste)
print("MLP:")
print("Acurácia: ", accuracy_score(y_teste,y_previsto))
print("Precisão: ", precision_score(y_teste,y_previsto))
print("Recall:   ", recall_score(y_teste,y_previsto))
print("F1 Score: ", f1_score(y_teste,y_previsto))

MLP:
Acurácia:  0.7918660287081339
Precisão:  0.7835294117647059
Recall:    0.8024096385542169
F1 Score:  0.7928571428571428


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [85]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(100),activation="logistic")
mlp_clf.fit(X_treino, y_treino)

y_previsto = mlp_clf.predict(X_teste)
print("MLP:")
print("Acurácia: ", accuracy_score(y_teste,y_previsto))
print("Precisão: ", precision_score(y_teste,y_previsto))
print("Recall:   ", recall_score(y_teste,y_previsto))
print("F1 Score: ", f1_score(y_teste,y_previsto))

MLP:
Acurácia:  0.7894736842105263
Precisão:  0.7893462469733656
Recall:    0.7855421686746988
F1 Score:  0.7874396135265701


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [86]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(10,10,10))
mlp_clf.fit(X_treino, y_treino)

y_previsto = mlp_clf.predict(X_teste)
print("MLP:")
print("Acurácia: ", accuracy_score(y_teste,y_previsto))
print("Precisão: ", precision_score(y_teste,y_previsto))
print("Recall:   ", recall_score(y_teste,y_previsto))
print("F1 Score: ", f1_score(y_teste,y_previsto))

MLP:
Acurácia:  0.8026315789473685
Precisão:  0.7880184331797235
Recall:    0.8240963855421687
F1 Score:  0.8056537102473499


In [87]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(20))
mlp_clf.fit(X_treino, y_treino)

y_previsto = mlp_clf.predict(X_teste)
print("MLP:")
print("Acurácia: ", accuracy_score(y_teste,y_previsto))
print("Precisão: ", precision_score(y_teste,y_previsto))
print("Recall:   ", recall_score(y_teste,y_previsto))
print("F1 Score: ", f1_score(y_teste,y_previsto))

MLP:
Acurácia:  0.7942583732057417
Precisão:  0.7845433255269321
Recall:    0.8072289156626506
F1 Score:  0.7957244655581949


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [88]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(20, 4))
mlp_clf.fit(X_treino, y_treino)

y_previsto = mlp_clf.predict(X_teste)
print("MLP:")
print("Acurácia: ", accuracy_score(y_teste,y_previsto))
print("Precisão: ", precision_score(y_teste,y_previsto))
print("Recall:   ", recall_score(y_teste,y_previsto))
print("F1 Score: ", f1_score(y_teste,y_previsto))

MLP:
Acurácia:  0.7954545454545454
Precisão:  0.7811059907834101
Recall:    0.8168674698795181
F1 Score:  0.7985865724381624


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


#### <font color='red'>*Treinamento de várias redes neurais artificiais, empregando todas as técnicas vistas durante o semestre*</font>

#### Automatizar os testes com GridSearchCV

In [89]:
from sklearn.model_selection import GridSearchCV

param_grid = [
    {'hidden_layer_sizes':[(10),(20),(30),(10,10),(20,20),(20,10)],
     'activation': ['logistic', 'tam', 'relu']},
]

mlp_clf = MLPClassifier(max_iter=500)
grid_search = GridSearchCV(mlp_clf, param_grid, scoring='recall', n_jobs=-1)
grid_search.fit(X_treino, y_treino)

GridSearchCV(estimator=MLPClassifier(max_iter=500), n_jobs=-1,
             param_grid=[{'activation': ['logistic', 'tam', 'relu'],
                          'hidden_layer_sizes': [10, 20, 30, (10, 10), (20, 20),
                                                 (20, 10)]}],
             scoring='recall')

Melhor configuração segundo o GridSearchCV e segundo a arquitetura passada.

In [90]:
grid_search.best_params_

{'activation': 'relu', 'hidden_layer_sizes': (20, 10)}

In [92]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(20),activation="relu")
mlp_clf.fit(X_treino, y_treino)

y_previsto = mlp_clf.predict(X_teste)
print("MLP:")
print("Acurácia: ", accuracy_score(y_teste,y_previsto))
print("Precisão: ", precision_score(y_teste,y_previsto))
print("Recall:   ", recall_score(y_teste,y_previsto))
print("F1 Score: ", f1_score(y_teste,y_previsto))

MLP:
Acurácia:  0.8026315789473685
Precisão:  0.7948113207547169
Recall:    0.8120481927710843
F1 Score:  0.803337306317044


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [93]:
y_previsto = grid_search.best_estimator_.predict(X_teste)
print("Best MLP:")
print("Acurácia: ", accuracy_score(y_teste,y_previsto))
print("Precisão: ", precision_score(y_teste,y_previsto))
print("Recall:   ", recall_score(y_teste,y_previsto))
print("F1 Score: ", accuracy_score(y_teste,y_previsto))

Best MLP:
Acurácia:  0.7978468899521531
Precisão:  0.7887323943661971
Recall:    0.8096385542168675
F1 Score:  0.7978468899521531


#### Realizando o treinamento usando o TensorFlow

In [94]:
import tensorflow as tf
from tensorflow import keras

In [95]:
X_treino.shape[1:]

(10,)

In [96]:
def MLPKerasTF(hidden_layer_sizes=(20)):
    model = keras.models.Sequential()
    model.add(keras.layers.InputLayer(input_shape=X_treino.shape[1:]))
    for units in hidden_layer_sizes:
        model.add(keras.layers.Dense(units,activation=activation))
    model.add(keras.layers.Dense(2, activation="softmax"))
    model.compile(loss="sparse_categorical_crossentropy", optimizer="sgd", metrics=["accuracy"])
    model.summary()
    print("activation=",activation)
    return model

mlpKerasTF_clf = keras.wrappers.scikit_learn.KerasClassifier(MLPKerasTF)

In [97]:
from sklearn.model_selection import GridSearchCV

param_grid = [
    {'hidden_layer_sizes':[(10),(20),(30),(10,10),(20,20),(20,10)],
     'activation': ['logistic', 'tam', 'relu']},
]

mlp_clf = MLPClassifier(max_iter=500)
grid_search = GridSearchCV(mlp_clf, param_grid, scoring='recall', n_jobs=-1)
grid_search.fit(X_treino, y_treino)

GridSearchCV(estimator=MLPClassifier(max_iter=500), n_jobs=-1,
             param_grid=[{'activation': ['logistic', 'tam', 'relu'],
                          'hidden_layer_sizes': [10, 20, 30, (10, 10), (20, 20),
                                                 (20, 10)]}],
             scoring='recall')

In [98]:
grid_search.best_params_

{'activation': 'relu', 'hidden_layer_sizes': (10, 10)}

In [99]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(10,10),activation="relu")
mlp_clf.fit(X_treino, y_treino)

y_previsto = mlp_clf.predict(X_teste)
print("MLP:")
print("Acurácia: ", accuracy_score(y_teste,y_previsto))
print("Precisão: ", precision_score(y_teste,y_previsto))
print("Recall:   ", recall_score(y_teste,y_previsto))
print("F1 Score: ", f1_score(y_teste,y_previsto))

MLP:
Acurácia:  0.7966507177033493
Precisão:  0.7842227378190255
Recall:    0.8144578313253013
F1 Score:  0.7990543735224587


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [100]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y_previsto = grid_search.best_estimator_.predict(X_teste)
print("Best MLPKerasTF:")
print("Acurácia: ", accuracy_score(y_teste,y_previsto))
print("Precisão: ", precision_score(y_teste,y_previsto))
print("Recall:   ", recall_score(y_teste,y_previsto))
print("F1 Score: ", f1_score(y_teste,y_previsto))

Best MLPKerasTF:
Acurácia:  0.7966507177033493
Precisão:  0.7829099307159353
Recall:    0.8168674698795181
F1 Score:  0.7995283018867925


In [101]:
input_  = keras.layers.Input(shape=X_treino.shape[1:])
hidden1 = keras.layers.Dense(100,activation="relu")(input_)
hidden2 = keras.layers.Dense(100,activation="relu")(hidden1)
concat  = keras.layers.Concatenate()([input_,hidden2])
output  = keras.layers.Dense(1,activation="sigmoid")(concat)
modelDW   = keras.Model(inputs=[input_],outputs=[output])

modelDW.compile(loss="binary_crossentropy",
                optimizer="adam",
                metrics=["accuracy"])

In [102]:
import os
import time

run_id = time.strftime("run_%Y_%m_%d-%H_%M_%S")
root_logdir = os.path.join(os.curdir,"logs")
run_logdir = os.path.join(root_logdir,run_id)
print("logdir = ",run_logdir)

tensorboard_cb = keras.callbacks.TensorBoard(run_logdir)

# para forçar o treinamento a parar antecipadamente quando não houver progresso na minimização de erro
early_stopping_cb = keras.callbacks.EarlyStopping(patience=4,restore_best_weights=True)

# para alvar periodicamente o modelo treinado e poder recomeçar o treinamento em caso de pane no meio do treinamento
checkpoint_cb     = keras.callbacks.ModelCheckpoint("modelDW-Abalone.h5") # Arquivo formato HDF5

history = modelDW.fit(X_treino, 
                      y_treino, 
                      epochs=200, 
                      validation_split=0.2,
                      callbacks=[early_stopping_cb, 
                                 checkpoint_cb,
                                 tensorboard_cb])

logdir =  ./logs/run_2020_11_28-17_34_48
Epoch 1/200
 1/84 [..............................] - ETA: 0s - loss: 0.6343 - accuracy: 0.7812WARNING:tensorflow:From /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/summary_ops_v2.py:1277: stop (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
use `tf.profiler.experimental.stop` instead.
84/84 [==============================] - 1s 6ms/step - loss: 0.4935 - accuracy: 0.7601 - val_loss: 0.4877 - val_accuracy: 0.7399
Epoch 2/200
84/84 [==============================] - 0s 4ms/step - loss: 0.4491 - accuracy: 0.7919 - val_loss: 0.4607 - val_accuracy: 0.7713
Epoch 3/200
84/84 [==============================] - 0s 3ms/step - loss: 0.4311 - accuracy: 0.8050 - val_loss: 0.4475 - val_accuracy: 0.7862
Epoch 4/200
84/84 [==============================] - 0s 3ms/step - loss: 0.4241 - accuracy: 0.8065 - val_loss: 0.4450 - val_accuracy: 0.7877
Epoch 5/200
84/84 [============

In [103]:
y_previsto_rna_proba = modelDW.predict(X_teste)
y_previsto_rna_proba

array([[8.74648631e-01],
       [4.89481032e-01],
       [9.35416043e-01],
       [8.55267406e-01],
       [7.98400342e-01],
       [5.30637622e-01],
       [2.67520845e-01],
       [1.54137760e-01],
       [3.35352421e-02],
       [5.58300257e-01],
       [7.18178749e-01],
       [5.09880781e-02],
       [8.75384569e-01],
       [5.35106957e-02],
       [9.01726484e-02],
       [9.02718961e-01],
       [9.13016438e-01],
       [5.36544681e-01],
       [9.84206796e-01],
       [1.91492051e-01],
       [9.99677241e-01],
       [8.42051148e-01],
       [7.92458236e-01],
       [7.88549304e-01],
       [3.63044024e-01],
       [9.19682682e-02],
       [3.69511276e-01],
       [1.19031817e-01],
       [4.33384776e-01],
       [4.56139088e-01],
       [8.51828098e-01],
       [8.37530315e-01],
       [2.98691690e-02],
       [6.73698068e-01],
       [1.51722789e-01],
       [3.86847973e-01],
       [1.64127946e-02],
       [1.68204308e-03],
       [2.39056557e-01],
       [2.37023532e-02],


y_previsto_rna = y_previsto_rna_proba > 0.5
y_previsto_rna

In [105]:
print("RNA D&W:")
print("Acurácia: ", accuracy_score(y_teste,y_previsto_rna))
print("Precisão: ", precision_score(y_teste,y_previsto_rna))
print("Recall:   ", recall_score(y_teste,y_previsto_rna))
print("F1 Score: ", f1_score(y_teste,y_previsto_rna))

RNA D&W:
Acurácia:  0.8014354066985646
Precisão:  0.7848970251716247
Recall:    0.8265060240963855
F1 Score:  0.8051643192488263


#### <font color='red'>*Avaliação do desempenho de cada rede neural artificial*</font>

As redes de 10 camadas assim como redes de 20 camadas, com redes neurais internas de 4 camadas e 10 camandas internas apresentaram melhores resultados, assim como a função de ativação "relu" mostraram melhores resultados para o modelo preditivo.

#### <font color='red'>*Escolha da rede neural artificial final justificada e embasada no processo de avaliação de desempenho*</font>

#### <font color='blue'>A melhor arquitetura de rede artificial segundo os resultados das redes testadas foi a rede de (20) com função de ativação relu, pois a precisão de previsão chegou a praticamente 80% das previsões de que o abalone passado no teste tem mais de 10 anos, e em torno de 20% ele pode considerar como um falso positivo, se o modelo for ser usado para adotar medidas de conservação dos moluscos considerados filhotes para o consumo, o modelo iria protejer na sua grande maioria moluscos menores garantindo a consistência da espécie e do consumo controlado. </font>